/**
 * Autogenerated by bestpay-cloud-maven-plugin
 * DO NOT EDIT DIRECTLY
 *
 * @Copyright 2018 www.bestpay.io Inc. All rights reserved.
 * @Copyright 2018 www.bestpay.io Inc. All rights reserved.
 */

/**
 * @Copyright 2018 www.bestpay.io Inc. All rights reserved.
 */
package cn.kingnet.utp.scheduler.enums;

public enum JobTaskStatus {

    /** 初始化 */
    PREP,
    /** 等待 */
    WAITING,
    /** 正在运行 */
    RUNNING,
    /** 失败 */
    FAILED,
    /** 取消作务 */
    KILLED,
    /** 成功 */
    SUCCESS;

}
